### ISSUE TITLE
The type is misordered.

### ISSUE THREAD

**Issue by yjhmelody** [as-pect/as-pect#349]
This error is very strange. As-pect collects type information and does not guarantee a good correspondence.

I write a class A<T> and it subclasses. _byteLength is abstract method.

```
ERROR TS2322: Type '(this: assembly/UInt/UInt32/UInt32) => i32' is not assignable to type '(this: assembly/AbstractInt/AbstractInt<u64>) => i32'.

     _byteLength(): i32 {
     ~~~~~~~~~~~
 in assembly/UInt/UInt32.ts(21,5)

ERROR TS2322: Type '(this: assembly/UInt/UInt64/UInt64) => i32' is not assignable to type '(this: assembly/AbstractInt/AbstractInt<u32>) => i32'.

     _byteLength(): i32 {
     ~~~~~~~~~~~
 in assembly/UInt/UInt64.ts(21,5)
```

The above types are swapped.

The quantities of the various types below are correct, but they do not match the types.

```
ERROR TS2322: Type '(this: assembly/UInt/UInt16/UInt16) => i32' is not assignable to type '(this: assembly/AbstractInt/AbstractInt<u64>) => i32'.

     _byteLength(): i32 {
     ~~~~~~~~~~~
 in assembly/UInt/UInt16.ts(21,5)

ERROR TS2322: Type '(this: assembly/UInt/UInt32/UInt32) => i32' is not assignable to type '(this: assembly/AbstractInt/AbstractInt<u64>) => i32'.

     _byteLength(): i32 {
     ~~~~~~~~~~~
 in assembly/UInt/UInt32.ts(21,5)

ERROR TS2322: Type '(this: assembly/UInt/UInt16/UInt16) => i32' is not assignable to type '(this: assembly/AbstractInt/AbstractInt<u32>) => i32'.

     _byteLength(): i32 {
     ~~~~~~~~~~~
 in assembly/UInt/UInt16.ts(21,5)

ERROR TS2322: Type '(this: assembly/UInt/UInt64/UInt64) => i32' is not assignable to type '(this: assembly/AbstractInt/AbstractInt<u32>) => i32'.

     _byteLength(): i32 {
     ~~~~~~~~~~~
 in assembly/UInt/UInt64.ts(21,5)

ERROR TS2322: Type '(this: assembly/UInt/UInt32/UInt32) => i32' is not assignable to type '(this: assembly/AbstractInt/AbstractInt<u16>) => i32'.

     _byteLength(): i32 {
     ~~~~~~~~~~~
 in assembly/UInt/UInt32.ts(21,5)

ERROR TS2322: Type '(this: assembly/UInt/UInt64/UInt64) => i32' is not assignable to type '(this: assembly/AbstractInt/AbstractInt<u16>) => i32'.

     _byteLength(): i32 {
     ~~~~~~~~~~~
 in assembly/UInt/UInt64.ts(21,5)
```

**Comment by yjhmelody** [comment]
Maybe this is AS bug

**Comment by yjhmelody** [comment]
@MaxGraey  Can you take a look? Thanks!

**Comment by MaxGraey** [comment]
> And another strange thing:
> 
> ```
> ERROR TS2339: Property 'fromU8a' does not exist on type 'assembly/AbstractInt/AbstractInt'.
> 
>          expect<UInt32>(UInt32.fromU8a([0xff, 0xff, 0xff, 0x3f])).toStrictEqual(
>                                ~~~~~~~
>  in assembly/__tests__/UInt.spec.ts(214,31)
> ```
> 
> Why 'assembly/AbstractInt/AbstractInt' rather than `UInt32`

this known behaviour. In AS static class methods don't derived from base class. You should add it manually.

**Comment by yjhmelody** [comment]
> > And another strange thing:
> > ```
> > ERROR TS2339: Property 'fromU8a' does not exist on type 'assembly/AbstractInt/AbstractInt'.
> > 
> >          expect<UInt32>(UInt32.fromU8a([0xff, 0xff, 0xff, 0x3f])).toStrictEqual(
> >                                ~~~~~~~
> >  in assembly/__tests__/UInt.spec.ts(214,31)
> > ```
> > 
> > 
> > Why 'assembly/AbstractInt/AbstractInt' rather than `UInt32`
> 
> this known behaviour. In AS static class methods don't derived from base class. You should add it manually.

I know it. I mean why it do not report `Property 'fromU8a' does not exist on type 'UInt32'.`

**Comment by MaxGraey** [comment]
Hmm, good catch. That's definitely could be improved

**Comment by yjhmelody** [comment]
One thing to note is: the sub-type unit test is written in one file, if it is divided into multiple files, there is no such problem. So I'm not sure how this caused it

**Comment by yjhmelody** [comment]
@MaxGraey I reproduce it using `asc`, so it's as bug.

**Comment by jtenner** [comment]
Is this still a problem?

**Comment by yjhmelody** [comment]
Maybe not, I will reopen if it is still a problem.

Thx!
